/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export type Locale = 'pt-BR' | 'en-GB' | 'es-ES' | 'fr-FR'

export const localeOptions: { code: Locale; flag: string; short: string; label: string }[] = [
  { code: 'pt-BR', flag: '🇧🇷', short: 'PT', label: 'Português (Brasil)' },
  { code: 'en-GB', flag: '🇬🇧', short: 'EN', label: 'English (United Kingdom)' },
  { code: 'es-ES', flag: '🇪🇸', short: 'ES', label: 'Español (España)' },
  { code: 'fr-FR', flag: '🇫🇷', short: 'FR', label: 'Français (France)' },
]

const translations: Record<Locale, Record<string, string>> = {
  'pt-BR': {
    'nav.services':'Serviços','nav.about':'Sobre','nav.portfolio':'Portfólio','nav.contact':'Contato','nav.cta':'Fale conosco','nav.open':'Abrir menu','nav.language':'Selecionar idioma',
    'hero.badge':'Ideias audaciosas. Tecnologia sem limites.','hero.title1':'Criamos o digital que','hero.title2':'ninguém ignora.','hero.text':'Sites, landing pages, aplicativos e sistemas sob medida que transformam ideias em experiências digitais memoráveis.','hero.cta':'Tire sua ideia do papel','hero.projects':'Explorar projetos','hero.logo':'Símbolo AINAKA',
    'services.eyebrow':'O que fazemos','services.title':'Tecnologia que move negócios para frente.','services.description':'Da primeira ideia ao produto no ar, combinamos estratégia, design e engenharia para construir soluções que fazem sentido.',
    'service.1.title':'Sites institucionais','service.1.text':'Presença digital autêntica, rápida e pensada para posicionar sua marca.','service.2.title':'Landing pages','service.2.text':'Páginas de alta conversão com estratégia, clareza e impacto visual.','service.3.title':'Aplicativos','service.3.text':'Experiências web e mobile intuitivas, escaláveis e prontas para crescer.','service.4.title':'Sistemas sob medida','service.4.text':'Plataformas criadas ao redor do seu processo, não o contrário.','service.5.title':'Automações','service.5.text':'Integrações inteligentes para reduzir tarefas repetitivas e acelerar resultados.','service.6.title':'Evolução contínua','service.6.text':'Manutenção, performance e suporte para seu produto nunca parar no tempo.',
    'about.eyebrow':'Por trás da AINAKA','about.title1':'Dois sócios. Uma inquietação:','about.title2':'criar o extraordinário.','about.p1':'A AINAKA nasceu da vontade de unir tecnologia de verdade, design arrojado e proximidade. Somos uma agência nova, com energia para questionar o óbvio e construir produtos digitais que tenham personalidade e propósito.','about.p2':'Aqui, cada projeto é uma parceria. Escutamos, investigamos e transformamos desafios complexos em experiências simples de usar — e difíceis de esquecer.','about.card1':'Estratégia antes da tela.','about.card2':'Tecnologia com propósito.','about.card3':'Construímos juntos.','about.card3text':'Transparência e colaboração do início ao lançamento.',
    'portfolio.eyebrow':'Projetos selecionados','portfolio.title':'O futuro começa como uma ideia.','portfolio.description':'Enquanto nossos primeiros cases ganham vida, estas são amostras conceituais do tipo de experiência que queremos construir.','project.1.type':'Produto digital','project.2.type':'Site institucional','project.3.type':'Landing page',
    'contact.eyebrow':'Próximo capítulo','contact.title1':'Tem uma ideia pulsando?','contact.title2':'Vamos dar vida a ela.','contact.text':'Conte o que você imagina. Nós ajudamos a encontrar o caminho mais inteligente para construir.','contact.whatsapp':'Começar uma conversa','contact.email':'E-mail','contact.instagram':'Instagram',
    'footer.text':'© 2026 AINAKA. Tecnologia feita para marcar.','marquee':'DESIGN • CÓDIGO • MOVIMENTO • ESTRATÉGIA • EXPERIÊNCIA • ',
  },
  'en-GB': {
    'nav.services':'Services','nav.about':'About','nav.portfolio':'Portfolio','nav.contact':'Contact','nav.cta':'Talk to us','nav.open':'Open menu','nav.language':'Select language',
    'hero.badge':'Bold ideas. Limitless technology.','hero.title1':'We create digital experiences','hero.title2':'no one can ignore.','hero.text':'Websites, landing pages, apps and bespoke systems that turn ideas into memorable digital experiences.','hero.cta':'Bring your idea to life','hero.projects':'Explore projects','hero.logo':'AINAKA symbol',
    'services.eyebrow':'What we do','services.title':'Technology that moves businesses forward.','services.description':'From the first idea to launch, we combine strategy, design and engineering to build solutions that make sense.',
    'service.1.title':'Corporate websites','service.1.text':'An authentic, fast digital presence designed to position your brand.','service.2.title':'Landing pages','service.2.text':'High-converting pages with strategy, clarity and visual impact.','service.3.title':'Applications','service.3.text':'Intuitive, scalable web and mobile experiences built to grow.','service.4.title':'Bespoke systems','service.4.text':'Platforms designed around your process, not the other way round.','service.5.title':'Automation','service.5.text':'Smart integrations that reduce repetitive work and accelerate results.','service.6.title':'Continuous evolution','service.6.text':'Maintenance, performance and support so your product never stands still.',
    'about.eyebrow':'Behind AINAKA','about.title1':'Two partners. One ambition:','about.title2':'to create the extraordinary.','about.p1':'AINAKA was born from a desire to unite real technology, bold design and genuine collaboration. We are a new agency with the energy to question the obvious and build digital products with personality and purpose.','about.p2':'Every project is a partnership. We listen, investigate and transform complex challenges into experiences that are simple to use — and hard to forget.','about.card1':'Strategy before screens.','about.card2':'Technology with purpose.','about.card3':'We build together.','about.card3text':'Transparency and collaboration from discovery to launch.',
    'portfolio.eyebrow':'Selected projects','portfolio.title':'The future begins as an idea.','portfolio.description':'While our first cases come to life, these concepts show the kind of experiences we aim to create.','project.1.type':'Digital product','project.2.type':'Corporate website','project.3.type':'Landing page',
    'contact.eyebrow':'The next chapter','contact.title1':'Got an idea taking shape?','contact.title2':'Let’s bring it to life.','contact.text':'Tell us what you imagine. We will help find the smartest way to build it.','contact.whatsapp':'Start a conversation','contact.email':'Email','contact.instagram':'Instagram',
    'footer.text':'© 2026 AINAKA. Technology built to make an impact.','marquee':'DESIGN • CODE • MOTION • STRATEGY • EXPERIENCE • ',
  },
  'es-ES': {
    'nav.services':'Servicios','nav.about':'Nosotros','nav.portfolio':'Portafolio','nav.contact':'Contacto','nav.cta':'Hablemos','nav.open':'Abrir menú','nav.language':'Seleccionar idioma',
    'hero.badge':'Ideas audaces. Tecnología sin límites.','hero.title1':'Creamos lo digital que','hero.title2':'nadie puede ignorar.','hero.text':'Sitios web, landing pages, aplicaciones y sistemas a medida que convierten ideas en experiencias digitales memorables.','hero.cta':'Haz realidad tu idea','hero.projects':'Explorar proyectos','hero.logo':'Símbolo AINAKA',
    'services.eyebrow':'Qué hacemos','services.title':'Tecnología que impulsa negocios.','services.description':'Desde la primera idea hasta el lanzamiento, combinamos estrategia, diseño e ingeniería para crear soluciones con sentido.',
    'service.1.title':'Sitios corporativos','service.1.text':'Una presencia digital auténtica, rápida y diseñada para posicionar tu marca.','service.2.title':'Landing pages','service.2.text':'Páginas de alta conversión con estrategia, claridad e impacto visual.','service.3.title':'Aplicaciones','service.3.text':'Experiencias web y móviles intuitivas, escalables y listas para crecer.','service.4.title':'Sistemas a medida','service.4.text':'Plataformas creadas alrededor de tu proceso, no al revés.','service.5.title':'Automatizaciones','service.5.text':'Integraciones inteligentes para reducir tareas repetitivas y acelerar resultados.','service.6.title':'Evolución continua','service.6.text':'Mantenimiento, rendimiento y soporte para que tu producto nunca se detenga.',
    'about.eyebrow':'Detrás de AINAKA','about.title1':'Dos socios. Una inquietud:','about.title2':'crear lo extraordinario.','about.p1':'AINAKA nació del deseo de unir tecnología real, diseño audaz y cercanía. Somos una agencia nueva, con energía para cuestionar lo obvio y crear productos digitales con personalidad y propósito.','about.p2':'Cada proyecto es una colaboración. Escuchamos, investigamos y transformamos desafíos complejos en experiencias fáciles de usar y difíciles de olvidar.','about.card1':'Estrategia antes que pantallas.','about.card2':'Tecnología con propósito.','about.card3':'Construimos juntos.','about.card3text':'Transparencia y colaboración desde el inicio hasta el lanzamiento.',
    'portfolio.eyebrow':'Proyectos seleccionados','portfolio.title':'El futuro comienza como una idea.','portfolio.description':'Mientras nuestros primeros casos cobran vida, estos conceptos muestran las experiencias que queremos crear.','project.1.type':'Producto digital','project.2.type':'Sitio corporativo','project.3.type':'Landing page',
    'contact.eyebrow':'Próximo capítulo','contact.title1':'¿Tienes una idea en mente?','contact.title2':'Vamos a darle vida.','contact.text':'Cuéntanos qué imaginas. Te ayudaremos a encontrar la forma más inteligente de construirlo.','contact.whatsapp':'Iniciar una conversación','contact.email':'Correo electrónico','contact.instagram':'Instagram',
    'footer.text':'© 2026 AINAKA. Tecnología creada para impactar.','marquee':'DISEÑO • CÓDIGO • MOVIMIENTO • ESTRATEGIA • EXPERIENCIA • ',
  },
  'fr-FR': {
    'nav.services':'Services','nav.about':'À propos','nav.portfolio':'Portfolio','nav.contact':'Contact','nav.cta':'Parlons-en','nav.open':'Ouvrir le menu','nav.language':'Choisir la langue',
    'hero.badge':'Des idées audacieuses. Une technologie sans limites.','hero.title1':'Nous créons le digital que','hero.title2':'personne n’ignore.','hero.text':'Sites web, landing pages, applications et systèmes sur mesure qui transforment les idées en expériences numériques mémorables.','hero.cta':'Donnez vie à votre idée','hero.projects':'Explorer les projets','hero.logo':'Symbole AINAKA',
    'services.eyebrow':'Notre savoir-faire','services.title':'La technologie qui fait avancer les entreprises.','services.description':'De la première idée au lancement, nous combinons stratégie, design et ingénierie pour créer des solutions pertinentes.',
    'service.1.title':'Sites institutionnels','service.1.text':'Une présence numérique authentique, rapide et pensée pour positionner votre marque.','service.2.title':'Landing pages','service.2.text':'Des pages à forte conversion, alliant stratégie, clarté et impact visuel.','service.3.title':'Applications','service.3.text':'Des expériences web et mobiles intuitives, évolutives et prêtes à grandir.','service.4.title':'Systèmes sur mesure','service.4.text':'Des plateformes conçues autour de vos processus, et non l’inverse.','service.5.title':'Automatisations','service.5.text':'Des intégrations intelligentes pour réduire les tâches répétitives et accélérer les résultats.','service.6.title':'Évolution continue','service.6.text':'Maintenance, performance et accompagnement pour faire évoluer votre produit.','about.eyebrow':'Derrière AINAKA','about.title1':'Deux associés. Une ambition :','about.title2':'créer l’extraordinaire.','about.p1':'AINAKA est née de l’envie d’unir technologie, design audacieux et proximité. Nous sommes une jeune agence prête à questionner l’évidence et à créer des produits numériques avec personnalité et sens.','about.p2':'Chaque projet est un partenariat. Nous écoutons, explorons et transformons les défis complexes en expériences simples à utiliser — et difficiles à oublier.','about.card1':'La stratégie avant les écrans.','about.card2':'La technologie avec du sens.','about.card3':'Nous construisons ensemble.','about.card3text':'Transparence et collaboration, de la découverte au lancement.',
    'portfolio.eyebrow':'Projets sélectionnés','portfolio.title':'Le futur commence par une idée.','portfolio.description':'En attendant nos premières réalisations, ces concepts illustrent les expériences que nous souhaitons créer.','project.1.type':'Produit numérique','project.2.type':'Site institutionnel','project.3.type':'Landing page',
    'contact.eyebrow':'Le prochain chapitre','contact.title1':'Une idée vous anime ?','contact.title2':'Donnons-lui vie.','contact.text':'Racontez-nous ce que vous imaginez. Nous trouverons la manière la plus intelligente de le construire.','contact.whatsapp':'Démarrer une conversation','contact.email':'E-mail','contact.instagram':'Instagram',
    'footer.text':'© 2026 AINAKA. Une technologie conçue pour marquer.','marquee':'DESIGN • CODE • MOUVEMENT • STRATÉGIE • EXPÉRIENCE • ',
  },
}

const I18nContext = createContext<{ locale: Locale; setLocale: (locale: Locale) => void; t: (key: string) => string } | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => (localStorage.getItem('ainaka-locale') as Locale) || 'pt-BR')
  useEffect(() => { localStorage.setItem('ainaka-locale', locale); document.documentElement.lang = locale }, [locale])
  const t = (key: string) => translations[locale][key] ?? translations['pt-BR'][key] ?? key
  return <I18nContext.Provider value={{ locale, setLocale, t }}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used inside I18nProvider')
  return value
}
