/* eslint-disable react/jsx-key */
import { useState, type FormEvent, type ReactNode } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, Send } from 'lucide-react'
import Logo from './Logo'

const Field = ({ label, name, children, required = true, hint }: { label: string; name: string; children?: ReactNode; required?: boolean; hint?: string }) => <label className="block text-sm text-white/70"><span className="font-medium text-white">{label}</span>{hint && <span className="mt-1 block text-xs leading-5 text-white/35">{hint}</span>}{children ?? <input name={name} required={required} className="admin-input" />}</label>
const Area = ({ label, name, hint, required = true }: { label: string; name: string; hint?: string; required?: boolean }) => <Field label={label} name={name} hint={hint} required={required}><textarea name={name} required={required} rows={4} className="admin-input resize-y" /></Field>

export default function BriefingPage() {
  const [step, setStep] = useState(0); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const [startedAt] = useState(() => Date.now())
  const sections = [
    <div className="space-y-5"><h2 className="briefing-title">Contato e dados básicos</h2><Field label="Seu nome" name="contactName"/><Field label="E-mail" name="email"><input name="email" type="email" required className="admin-input"/></Field><Field label="Nome da empresa ou profissional" name="companyName"/><Field label="WhatsApp comercial" name="whatsapp"/><Field label="Endereço de site desejado" name="desiredDomain" hint="Ex.: clinicasilva.com.br"/><Field label="Instagram e outras redes sociais" name="socialNetworks"/><Field label="Endereço físico" name="physicalAddress" required={false}/></div>,
    <div className="space-y-5"><h2 className="briefing-title">O que você vende e para quem</h2><Area label="Qual produto ou serviço esta página promoverá?" name="mainOffer"/><Area label="Quem é o seu cliente ideal?" name="targetAudience" hint="Descreva perfil, idade, profissão, localização e interesses, se souber."/><Area label="Qual é a maior dor que você resolve?" name="mainPain"/><Area label="Existe uma oferta ou condição especial?" name="specialOffer" hint="Ex.: orçamento gratuito, primeira consulta com desconto." required={false}/></div>,
    <div className="space-y-5"><h2 className="briefing-title">Diferenciais e autoridade</h2><Area label="Por que contratar você e não a concorrência?" name="differentials" hint="Liste de 3 a 5 diferenciais fortes."/><Area label="Tempo de mercado e números de autoridade" name="authority" hint="Ex.: 10 anos de experiência, mais de 500 clientes."/><Area label="Depoimentos ou avaliações" name="testimonials" hint="Cole relatos ou links para prints." required={false}/></div>,
    <div className="space-y-5"><h2 className="briefing-title">Identidade visual e estilo</h2><Field label="Cores principais da marca" name="brandColors"/><Field label="Estilo visual desejado" name="visualStyle"><select name="visualStyle" required className="admin-input"><option value="">Selecione</option><option>Minimalista / Clean</option><option>Corporativo / Sério</option><option>Moderno / Tecnológico</option><option>Vibrante / Comercial</option><option>Outro</option></select></Field><Area label="Links para logo, fotos e materiais" name="assetLinks" hint="Compartilhe links do Google Drive, Dropbox ou outro armazenamento."/><Area label="Sites que você gosta como referência" name="references" hint="Informe de 1 a 2 links e explique o que gostou."/></div>,
    <div className="space-y-5"><h2 className="briefing-title">Objetivo principal da página</h2><div className="grid gap-3">{['Chamar direto no WhatsApp','Preencher formulário de orçamento','Comprar via checkout externo'].map((item)=><label key={item} className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm text-white/70"><input type="radio" name="mainGoal" value={item} required className="accent-neon-purple"/>{item}</label>)}</div><Area label="Existe alguma ação secundária desejada?" name="secondaryGoal" required={false}/></div>,
    <div className="space-y-5"><h2 className="briefing-title">Perguntas frequentes</h2><p className="text-sm leading-6 text-white/45">Informe dúvidas e respostas resumidas.</p><Area label="Pergunta e resposta 1" name="faq1"/><Area label="Pergunta e resposta 2" name="faq2"/><Area label="Pergunta e resposta 3" name="faq3"/><Area label="Perguntas adicionais" name="faqAdditional" required={false}/></div>,
    <div className="space-y-5"><h2 className="briefing-title">Planejamento</h2><Field label="Quando gostaria de lançar a página?" name="deadline"/><Field label="Faixa de investimento prevista" name="budget"><select name="budget" required className="admin-input"><option value="">Selecione</option><option>Ainda não defini</option><option>Até R$ 1.500</option><option>R$ 1.500 a R$ 3.000</option><option>R$ 3.000 a R$ 6.000</option><option>Acima de R$ 6.000</option></select></Field><Area label="Observações finais" name="additionalNotes" required={false}/><label className="flex items-start gap-3 text-xs leading-5 text-white/50"><input type="checkbox" name="consent" required className="mt-1 accent-neon-purple"/>Autorizo a AINAKA a utilizar estas informações para analisar minha solicitação e entrar em contato comigo.</label><input name="website" tabIndex={-1} autoComplete="off" className="hidden"/></div>,
  ]
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setError('');const form=new FormData(event.currentTarget);const base={contactName:String(form.get('contactName')),companyName:String(form.get('companyName')),email:String(form.get('email')),whatsapp:String(form.get('whatsapp')),website:String(form.get('website')),consent:form.get('consent')==='on',startedAt};const answers=Object.fromEntries(Array.from(form.entries()).filter(([key])=>!['contactName','companyName','email','whatsapp','website','consent'].includes(key)));try{const response=await fetch('/api/briefings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,answers})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSent(true);window.scrollTo({top:0,behavior:'smooth'})}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível enviar.')}finally{setSending(false)}}
  if(sent)return <main className="flex min-h-screen items-center justify-center px-5"><div className="glass-panel max-w-xl rounded-3xl p-10 text-center"><CheckCircle2 className="mx-auto text-emerald-300" size={52}/><h1 className="mt-6 font-display text-3xl font-bold">Briefing recebido!</h1><p className="mt-4 leading-7 text-white/55">Obrigado pelas informações. A AINAKA analisará seu projeto e entrará em contato pelos dados informados.</p><a href="/" className="mt-7 inline-block rounded-full bg-white px-6 py-3 text-sm font-semibold text-void">Voltar ao site</a></div></main>
  return <main className="min-h-screen px-5 py-10 sm:py-16"><div className="mx-auto max-w-3xl"><a href="/"><Logo/></a><div className="mt-10"><span className="text-xs uppercase tracking-[.3em] text-neon-cyan">Briefing de landing page</span><h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Conte-nos sobre sua ideia.</h1><p className="mt-4 text-white/50">Etapa {step+1} de {sections.length}</p><div className="mt-4 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-neon-blue to-neon-pink transition-all" style={{width:`${((step+1)/sections.length)*100}%`}}/></div></div><form onSubmit={submit} className="glass-panel mt-8 rounded-3xl p-6 sm:p-9">{sections.map((section,index)=><div key={index} className={index===step?'block':'hidden'}>{section}</div>)}{error&&<p className="mt-5 text-sm text-red-300">{error}</p>}<div className="mt-8 flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep(step-1)} className="flex items-center gap-2 rounded-xl border border-white/10 px-5 py-3 text-sm text-white/60 disabled:invisible"><ArrowLeft size={16}/> Voltar</button>{step<sections.length-1?<button type="button" onClick={()=>setStep(step+1)} className="flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-void">Continuar <ArrowRight size={16}/></button>:<button disabled={sending} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-neon-blue to-neon-pink px-5 py-3 text-sm font-semibold"><Send size={16}/>{sending?'Enviando…':'Enviar briefing'}</button>}</div></form></div></main>
}
