import { useEffect, useState } from 'react'
import { ArrowUpRight } from 'lucide-react'
import SectionHeading from './SectionHeading'
import { useI18n, type Locale } from '../i18n/I18nContext'

type CmsProject = { id: number; slug: string; name: string; coverUrl?: string; websiteUrl?: string; technologies: string[]; translations: Partial<Record<Locale, { category: string; description: string }>>; featured: boolean }
const concepts = [
  { name: 'NOVA / Future Finance', typeKey: 'project.1.type', gradient: 'from-neon-blue/70 via-neon-violet/30 to-transparent', code: '01' },
  { name: 'Orbit / Urban Living', typeKey: 'project.2.type', gradient: 'from-neon-pink/60 via-neon-purple/25 to-transparent', code: '02' },
  { name: 'Pulse / Creative Lab', typeKey: 'project.3.type', gradient: 'from-neon-cyan/60 via-neon-blue/20 to-transparent', code: '03' },
]

export default function Portfolio() {
  const { t, locale } = useI18n()
  const [projects, setProjects] = useState<CmsProject[]>([])
  useEffect(() => { fetch('/api/projects').then((response) => response.ok ? response.json() : Promise.reject()).then(setProjects).catch(() => undefined) }, [])
  return <section id="portfolio" className="scroll-mt-24 px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow={t('portfolio.eyebrow')} title={t('portfolio.title')} description={t('portfolio.description')} />
    {projects.length > 0 ? <div className="grid gap-5 lg:grid-cols-3">{projects.map((project) => { const translated = project.translations?.[locale] ?? project.translations?.['pt-BR']; const logoOnly = project.slug === 'ihubsells'; const card = <article className="glass-panel group h-full overflow-hidden rounded-3xl border border-white/10"><div className={`relative aspect-[4/3] overflow-hidden ${logoOnly ? 'bg-white' : 'bg-gradient-to-br from-neon-blue/30 via-neon-purple/20 to-transparent'}`}>{project.coverUrl ? <img src={project.coverUrl} alt={project.name} className={`h-full w-full transition duration-700 group-hover:scale-105 ${logoOnly ? 'object-contain p-7' : 'object-cover'}`} /> : <div className="grid-overlay absolute inset-0" />}{project.featured && <span className="absolute left-4 top-4 rounded-full border border-white/15 bg-black/50 px-3 py-1 text-[10px] uppercase tracking-wider text-white/70 backdrop-blur">Destaque</span>}</div><div className="p-6"><div className="flex items-start justify-between gap-3"><div><span className="text-xs uppercase tracking-widest text-neon-cyan">{translated?.category || 'Projeto digital'}</span><h3 className="mt-2 font-display text-xl font-semibold text-white">{project.name}</h3></div><ArrowUpRight className="shrink-0 text-white/50 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-white" /></div>{translated?.description && <p className="mt-4 line-clamp-3 text-sm leading-6 text-white/50">{translated.description}</p>}{project.technologies?.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{project.technologies.map((technology) => <span key={technology} className="rounded-full bg-white/5 px-2.5 py-1 text-[10px] text-white/45">{technology}</span>)}</div>}</div></article>; return project.websiteUrl ? <a key={project.id} href={project.websiteUrl} target="_blank" rel="noreferrer">{card}</a> : <div key={project.id}>{card}</div> })}</div> : <div className="grid gap-5 lg:grid-cols-3">{concepts.map((project) => <article key={project.name} className="glass-panel group overflow-hidden rounded-3xl border border-white/10"><div className={`relative aspect-[4/3] overflow-hidden bg-gradient-to-br ${project.gradient}`}><div className="grid-overlay absolute inset-0 opacity-70" /><span className="absolute bottom-2 right-5 font-display text-8xl font-bold text-white/[.07]">{project.code}</span><div className="absolute left-1/2 top-1/2 h-24 w-24 -translate-x-1/2 -translate-y-1/2 rotate-45 rounded-3xl border border-white/20 bg-white/5 transition duration-500 group-hover:rotate-90 group-hover:scale-110" /></div><div className="flex items-center justify-between p-6"><div><span className="text-xs uppercase tracking-widest text-neon-cyan">{t(project.typeKey)}</span><h3 className="mt-2 font-display text-lg font-semibold text-white">{project.name}</h3></div><ArrowUpRight className="text-white/50" /></div></article>)}</div>}
  </div></section>
}
