import { useEffect, useMemo, useState } from 'react'
import { Save } from 'lucide-react'
import { contentSections, defaultTranslations, localeOptions, type Locale } from '../i18n/I18nContext'

type ContentRow = { locale: Locale; key: string; value: string }
type AllValues = Record<Locale, Record<string, string>>
const fieldLabel = (key: string) => { const last = key.split('.').at(-1); const labels: Record<string, string> = { eyebrow:'Chamada pequena',title:'Título',title1:'Título — primeira parte',title2:'Título em destaque',text:'Descrição',description:'Descrição',badge:'Selo superior',cta:'Botão principal',projects:'Botão de projetos',p1:'Primeiro parágrafo',p2:'Segundo parágrafo',card1:'Primeiro destaque',card2:'Segundo destaque',card3:'Terceiro destaque',card3text:'Descrição do terceiro destaque',marquee:'Texto da faixa animada',services:'Link Serviços',about:'Link Sobre',portfolio:'Link Portfólio',contact:'Link Contato',whatsapp:'Texto do WhatsApp',email:'Rótulo do e-mail',instagram:'Rótulo do Instagram',type:'Categoria' }; return labels[last ?? ''] ?? key }
const initialValues = (): AllValues => Object.fromEntries(localeOptions.map(({ code }) => [code, { ...defaultTranslations[code] }])) as AllValues

export default function ContentEditor({ setNotice }: { setNotice: (message: string) => void }) {
  const [values, setValues] = useState<AllValues>(initialValues)
  const [loading, setLoading] = useState(true)
  useEffect(() => { fetch('/api/content', { credentials: 'include' }).then((response) => response.json()).then((data: { content: ContentRow[] }) => { const next = initialValues(); for (const row of data.content ?? []) next[row.locale][row.key] = row.value; setValues(next) }).finally(() => setLoading(false)) }, [])
  const entries = useMemo(() => localeOptions.flatMap(({ code }) => contentSections.flatMap((section) => section.keys.map((key) => ({ locale: code, key, value: values[code][key] ?? '' })))), [values])
  const change = (locale: Locale, key: string, value: string) => setValues((current) => ({ ...current, [locale]: { ...current[locale], [key]: value } }))
  async function save() { setNotice('Salvando os quatro idiomas…'); const response = await fetch('/api/content', { method:'PUT', credentials:'include', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ entries }) }); if (!response.ok) { const data = await response.json(); setNotice(data.error ?? 'Não foi possível salvar.'); return } setNotice('Todos os idiomas foram salvos. Atualize o site para visualizar.') }
  if (loading) return <p className="text-white/50">Carregando conteúdo…</p>
  return <div><div><h1 className="font-display text-3xl font-bold">Conteúdo da landing page</h1><p className="mt-2 text-sm text-white/50">Cada texto possui quatro versões. Preencha todas antes de salvar.</p></div><div className="mt-8 space-y-5">{contentSections.map((section) => <section key={section.title} className="glass-panel rounded-2xl p-5 sm:p-7"><h2 className="font-display text-xl font-semibold">{section.title}</h2><div className="mt-6 space-y-7">{section.keys.map((key) => { const multiline = ['text','description','p1','p2','card3text'].some((part) => key.endsWith(part)); return <div key={key}><div className="mb-3 text-sm font-medium text-white/80">{fieldLabel(key)} <span className="ml-2 font-mono text-[10px] font-normal text-white/20">{key}</span></div><div className="grid gap-3 xl:grid-cols-2">{localeOptions.map((option) => <label key={option.code} className="block text-xs text-white/45"><span className="mb-1.5 flex items-center gap-2"><span className="text-base">{option.flag}</span>{option.label}</span>{multiline ? <textarea rows={3} value={values[option.code][key] ?? ''} onChange={(event) => change(option.code, key, event.target.value)} className="w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm leading-6 text-white outline-none focus:border-neon-purple" /> : <input value={values[option.code][key] ?? ''} onChange={(event) => change(option.code, key, event.target.value)} className="w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none focus:border-neon-purple" />}</label>)}</div></div>})}</div></section>)}</div><div className="sticky bottom-5 mt-6 flex justify-end"><button onClick={save} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-neon-blue to-neon-pink px-6 py-3 text-sm font-semibold shadow-xl"><Save size={17} /> Salvar os quatro idiomas</button></div></div>
}
